### ISSUE TITLE
docker build for imx8 not working out of the box

### ISSUE THREAD

**Issue by eurofun** [thesofproject/sof-docs#465]
The getting started nxp page mentions building inside a docker container as an option and refers to https://thesofproject.github.io/latest/getting_started/build-guide/build-with-docker.html
Too bad that the container installed after following this page doesn't contain an aarch64 toolchain. sof branch is a one week old 'main'.

Inside the container I had to 
`apt update && apt-get install gcc-aarch64-linux-gnu`

and make the following changes after the toolchain install was committed to a new container 'mysof':

```
diff --git a/scripts/build-tools.sh b/scripts/build-tools.sh
index 49f0eeaa7..f9e0afed0 100755
--- a/scripts/build-tools.sh
+++ b/scripts/build-tools.sh
@@ -38,7 +38,7 @@ reconfigure_build()
         mkdir -p "$BUILD_TOOLS_DIR"
 
         ( cd "$BUILD_TOOLS_DIR"
-          cmake -GNinja -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" "${SOF_REPO}/tools"
+          cmake -DCMAKE_TOOLCHAIN_FILE=../scripts/cross-arch64.cmake -GNinja -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" "${SOF_REPO}/tools"
         )
 }
 
diff --git a/scripts/docker-run.sh b/scripts/docker-run.sh
index 29d7ebc0f..573bbc88a 100755
--- a/scripts/docker-run.sh
+++ b/scripts/docker-run.sh
@@ -44,4 +44,4 @@ docker run -i -v "${SOF_TOP}":/home/sof/work/sof.git \
        --env https_proxy="$https_proxy" \
        --user "$(id -u)" \
        $SOF_DOCKER_RUN \
-       thesofproject/sof "$@"
+       mysof "$@"
diff --git a/scripts/xtensa-build-all.sh b/scripts/xtensa-build-all.sh
index 05cb8f13d..233e32f4d 100755
--- a/scripts/xtensa-build-all.sh
+++ b/scripts/xtensa-build-all.sh
@@ -190,7 +190,7 @@ fi
 
 OLDPATH=$PATH
 CURDIR="$(pwd)"
-
+git config --global --add safe.directory /home/sof/work/sof.git
 # build platforms
 for platform in "${PLATFORMS[@]}"
 do
``` 

For the xtensa toolchain the docs say 'contact nxp support' but as far as I know everybody can download them directly from cadence (after some registration). So some installation instructions could be helpful - personally I don't care right now as gcc does its job sufficiently good.

Under https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html there are only instructions on how to disable suspend for intel (plus there is one tiny spelling error on this page: sof-loggerr ). 
For imx8mp this works:
`/sys/class/devlink/platform:power-domains:audiomix-pd--platform:3b6e8000.dsp/consumer/power# echo on>control`

https://thesofproject.github.io/latest/developer_guides/topology/topology.html#debug-topology :
```
root@d73e8cbcbd51:~/work/sof.git/tools/topology/topology1# m4 -I m4 -I common -I platform/common --define=GRAPH sof-imx8-nocodec.m4 2> test.dot
root@d73e8cbcbd51:~/work/sof.git/tools/topology/topology1# cat test.dot 
"PCM0P"->"BUF1.0"
"BUF1.0"->"PGA1.0"
"PGA1.0"->"BUF1.1"
"BUF1.1"->"ESAI0.OUT"

dot -Tpng -o a.png tools/topology/topology1/test.dot
Error: tools/topology/topology1/test.dot: syntax error in line 1 near '"'
```

Isn't there a `digraph G {}` missing? At least I can't get dot to produce an image without that... I guess it's debatable whether this is 
 a) related to the original topic of this issue (sorry) and b) should be fixed in the documentation or elsewhere.

**Comment by dbaluta** [comment]
@eurofun  thanks for opening this issue. 

1) it is not clear for me what is the docker problem. We use docker with CI to build SOF Firmware

https://github.com/thesofproject/sof/actions/runs/4857833763/jobs/8658689993?pr=7546

and all works well.

I guess your problem is that you cannot build the sof-logger for ARM64, right? Then yes, you are right the scripts are not customized for building ARM64 userspace. 

2) For Xtensa toolchain. Yes, I think some part of the toolchain can be obtained from Xtensa but you still need IMX specific configuration files to have a build running on IMX8 DSP.

3)
> For imx8mp this works:
/sys/class/devlink/platform:power-domains:audiomix-pd--platform:3b6e8000.dsp/consumer/power# echo on>control

 Do you suggest that we should add a chapter on how to disable suspend on IMX?

4) sof-imx8-nocodec.m4 is legacy stuff and we kind of skipped supporting it. But anyhow, if you want to draw the graph  you can use:

https://github.com/thesofproject/sof-test/blob/main/tools/tplgtool2.py

./tplgtool2.py -d graph ~/work/repos/sof/tools/build_tools/topology/topology1/production/sof-imx8-nocodec.tplg 

May I ask you what is the project you are working on? And what are you trying to achieve?

**Comment by dbaluta** [comment]
@eurofun 

1. Maybe this warning has something to do with it:

```
Warning: this script should be run as user ID 1000 to match the container's account
```

2. Oh, all right. Didn't try it either.

3. Care to send a patch? We use this: https://github.com/thesofproject/sof-docs. Otherwise, will add it on my to do list for next weeks.

4. nocodec topologies were used few years ago when we started development and are not currently maintained. You can have a look for real hardware dts here: 

https://github.com/nxp-imx/linux-imx/tree/lf-6.1.y/arch/arm64/boot/dts/freescale

Just grep for dts that contain SOF in name.
